### PR TITLE
Optionally play a sound when the timer ends

### PR DESCRIPTION
**Pull request by McPringle**

### CODE REVIEW

**Comment by nowsprinting** [comment]
Thank you your pull request.

What is the motivation for this feature?
If you turn on "Play Sound" in the IntelliJ IDEs Notifications settings when mob timer expired, you can make it beep.

**Comment by McPringle** [comment]
Please excuse the delay in my reply. The motivation for this extension is quite simple: The notification on timeout is hardly noticeable on our large monitors in the office (43 inches). Therefore, the wish was expressed several times to report the timeout acoustically as well. 

IntelliJ can beep when displaying a notification. This is quite nice, but we do not find it sufficient. Moreover, it is the same sound for all notifications and, as far as we know, it cannot be changed. We would like the audio to be different. We also have the additional idea that the user should also be able to select their own audio file. So you can record a little sequence in your local language, for example, "Attention, don't miss driver change". Due to time constraints, we have postponed this and will gladly deliver this extension later.

I hope our arguments convince you. We think your plugin is awesome!

Greetings from Lucerne

**Comment by nowsprinting** [comment]
Thank you for your reply.
I understand your motivation. Please give me some more time to consider.

However, I think we should originally extend the notifications feature.
I will consider merging with the assumption that I will revert if I can achieve it in the future with notifications.

**Comment by McPringle** [comment]
To revert this PR later when the same feature can be done with the integrated notifications is absolutely fine!

**Comment by McPringle** [comment]
What I want for Christmas: It would be quite awesome to see this feature in a new release of the plugin! I could then present this to my work colleagues after the vacation. They are waiting for it... 🎅

**Comment by nowsprinting** [comment]
I'm sorry. I'm so busy right now that I can't get a lot of time.
If you have time, I want you to write a description for this PR.

**Review by nowsprinting — CHANGES_REQUESTED** [review]
* Write a description for this PR
* Revert update Kotlin and dependency libraries. (If you need, please send out another PR)

**Pull request closed without merging**
